apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 4
  selector: 
    app: nginx
  template: 
    metadata:
     labels:
      app: nginx
    spec: 
      containers:
      - image:  nginximage
        name:  my-name
        ports:
        - containerPort:  80
          protocol: TCP     