apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
  labels:
    app: my-statefulset
spec: 
    selector: 
      matchLabels:
        app: my-statefulset
    replicas: 5
    template:
      metadata:
        labels:
          app: my-statefulset
      spec:
        containers: 
        - image: mysql:latest
          name: my-statefulset-conatiner
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "12345678"

 